// Generated by CoffeeScript 2.3.0
var adversaire, boussole, changeJ, curseur, destination, joueur, nom, origine;

joueur = "tang";

nom = {
  "tang": "tangue",
  "dog": "chiens"
};

adversaire = {
  "tang": "dog",
  "dog": "tang"
};

curseur = {
  "tang": "img/titang.png",
  "dog": "img/tichien.png"
};

boussole = ["g", "c", "d"];

origine = "c1";

destination = "c2";

changeJ = function() {
  joueur = adversaire[joueur];
  $(".quijoue").text(nom[joueur]);
  $(".est, .nord, .ne, .nw").css("cursor", `url('${curseur[joueur]}'), pointer`);
  return $("#dessinJ").toggleClass(adversaire[joueur]).toggleClass(joueur);
};

$(function() {
  var unCoup, vide, videbis;
  $(".regle, #graphe").draggable();
  vide = function() {
    return (!$(`#${destination}`).hasClass("tang")) && (!$(`#${destination}`).hasClass("dog"));
  };
  videbis = function() {
    return (!$(`#${origine}`).hasClass("tang")) && (!$(`#${origine}`).hasClass("dog"));
  };
  unCoup = function(how, who) {
    if (how === "est") {
      if (($(`#${origine}`).hasClass(joueur)) && vide()) {
        $(`#${origine}`).removeClass(joueur);
        $(`#${destination}`).addClass(joueur);
        return changeJ();
      } else if (videbis() && ($(`#${destination}`).hasClass(joueur))) {
        $(`#${destination}`).removeClass(joueur);
        $(`#${origine}`).addClass(joueur);
        return changeJ();
      }
    } else {
      if (($(`#${origine}`).hasClass(joueur)) && vide()) {
        $(`#${origine}`).removeClass(joueur);
        $(`#${destination}`).addClass(joueur);
        return changeJ();
      } else if (($(`#${destination}`).hasClass(joueur)) && videbis() && joueur === "tang") {
        $(`#${destination}`).removeClass("tang");
        $(`#${origine}`).addClass("tang");
        return changeJ();
      }
    }
  };
  $(".nord").on('click', function() {
    origine = "" + boussole[$(this).index() / 2] + ((7 - $(this).parent().index()) / 2);
    destination = "" + boussole[$(this).index() / 2] + ((7 - $(this).parent().index()) / 2 + 1);
    return unCoup("nord", joueur);
  });
  $(".est").on('click', function() {
    origine = "" + boussole[($(this).index() - 1) / 2] + ((8 - $(this).parent().index()) / 2);
    destination = "" + boussole[($(this).index() + 1) / 2] + ((8 - $(this).parent().index()) / 2);
    return unCoup("est", joueur);
  });
  $(".ne").on('click', function() {
    origine = "" + boussole[($(this).index() - 1) / 2] + ((7 - $(this).parent().index()) / 2);
    destination = "" + boussole[($(this).index() + 1) / 2] + ((9 - $(this).parent().index()) / 2);
    return unCoup("ne", joueur);
  });
  return $(".nw").on('click', function() {
    origine = "" + boussole[($(this).index() + 1) / 2] + ((7 - $(this).parent().index()) / 2);
    destination = "" + boussole[($(this).index() - 1) / 2] + ((9 - $(this).parent().index()) / 2);
    return unCoup("nw", joueur);
  });
});
